### ISSUE TITLE
logging:

### ISSUE THREAD

**Issue by iFirebrand** [islishude/geth-docker#9]
Something is off with the logging config in the docker-compose.yml. Container doesn't start with the code as-is. Commenting out everything in the `logging` section lets you move forward.

**Comment by islishude** [comment]
What version of compose do you use? it should work with compose v2

**Comment by islishude** [comment]
I just tested the compose file, it works for me.

**Comment by iFirebrand** [comment]
The error:

```
~/eth2 % docker-compose up geth
Recreating 2495f12b5f28_geth ... error

ERROR: for 2495f12b5f28_geth  Cannot create container for service geth: json: cannot unmarshal number into Go struct field LogConfig.HostConfig.LogConfig.Config of type string

ERROR: for geth  Cannot create container for service geth: json: cannot unmarshal number into Go struct field LogConfig.HostConfig.LogConfig.Config of type string
ERROR: Encountered errors while bringing up the project.
```

The `docker-compose` is version 1.29.2

The `docker desktop` is v.4.11.1

The docker desktop uses Docker Compose V2 (box checked)

**Comment by islishude** [comment]
You can enable compose v2 in docker desktop preferences

<img width="897" alt="image" src="https://user-images.githubusercontent.com/24730006/187939734-570de65c-8dfc-449a-a911-0bdcb36ca8e5.png">
